/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUlYNUt2VmdQdmx0UVY1WTNpbXQxTGtPUzd2K24rY1N2QUwzS2xzK1hYUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWTBYeTFyd0pOSFE5V2dZTHp1bEQrbUVxM2ZmTU10Z25NazVlV0dmaXl6QT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvSzNRMW41S1ZpUXBXUVBRZ3pNUkltTVE0S3dVc09YV2dXUkpINGhKL0YwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJYcDRmbjJOUnc4L2FQdjNZWXZuSlVxb2VST3RlTHp5MWNkaGsyOWpXNGxrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFGWEtuVkg0Q3VyRW5SWmUyVFR3QmpJcVJ4U1VXVE92QytEY1lpV3dLWGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlRWRFdqbmpQbDlVSjl1K3NISGJpQzdLUzhmOWJXbU5kWUhWdDhrSmVrVmc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEtZT1dwZDdlVmk1aWp6VVpXdkp5dkJ1Qk9GRVNwdHF2c3lTNlUyWWJsOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicHJ1OW4rK0VzSXovTE5OUFkyVWloTktmbG12YzFhbVJyOElTSnhWM2lTRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZQQU9qNW5QMWFtQXhCMDQ5NjZGTmtrK0lYTk9oM0JYTzZsM1QxaGhpdzVRajNDM1prSXlXVFRvZVBlUkNURVJuVTYzWXRVemcwV1NLK0xudW5yNEJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEzLCJhZHZTZWNyZXRLZXkiOiJSSVNwRXl4WGlLY3BndlIyR1A3ZFY5VzgzcnBydjZkTmdnNTRoaVZqdk5ZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3ZUxuclFuSVRsbWNuek1ZTk52al9RIiwicGhvbmVJZCI6ImJmOGQ2YmM1LWRjZjUtNDk5Ni1iYWNjLWI0YTAwMGI3MWJjYyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJacFlIQkNDd0xiNHV4QUZKUGR6ZXFHdGZma1E9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0wzNkdVT1BVUHlmVjVIdzM5SFpmWFdvb3NVPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjZRS0xQUjFDIiwibWUiOnsiaWQiOiIyNTQxMTIxOTIxMTk6NzFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2Qgs2GzLrwnZCAzYbMuvCdkJLNhsy68J2QhM2GzLrwnZCYzYbMuvCdkJHNhsy68J2Qh82GzLrwnZCOzYbMuvCdkIPNhsy68J2QhM2GzLrwnZCSzYbMuiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTFdQMVpzQkVJanYvN2NHR0FrZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUmZMWHVkb05xZDd3VFpFT1VzMWhGbTBRWnR4dTRabU00RlJsTTQzcFBncz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiN3Z5Uk45SHA4Rk11WkZHditmakJZMkV2ODNKdjRRajhQbFJsSUR1SzBnVXhDSGpLaUVFaGxsak0yK3hSb2E2SFVtTkhUQTd0MmhNNFF1SEpQQVlCQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IjZ4RXBxSHhwUWV5RWJCejlHRDZPNEhFTnJMRm9DZnQ0cDJnUWtoZzZGNElxNnVnaXlZZG1Nd2xvbFhRTnltZ0R6YSt3NTlYSXByajFJcHZxbWVhRkJnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0MTEyMTkyMTE5OjcxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVYeTE3bmFEYW5lOEUyUkRsTE5ZUlp0RUdiY2J1R1pqT0JVWlRPTjZUNEwifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgwNTEwOTUsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSWFlIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'CASRYRHODES🌟';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254112192119';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'CASRYRHODES🌟';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
